# Generated by Django 5.0.4 on 2024-05-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_apiuser_apikeysforbots'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeysforbots',
            name='key_about',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
