# Generated by Django 5.0.4 on 2024-05-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_apikeysforbots_key_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeysforbots',
            name='key',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
